### ISSUE TITLE
plone.app.z3cform.wysiwyg.WysiwygFieldWidget is deprecated

### ISSUE THREAD

**Issue by djowett** [collective/dexterity.membrane#39]
The following error is reported on `bio` field in `IMember`
```
DeprecationWarning: plone.app.z3cform.wysiwyg.WysiwygFieldWidget is deprecated and will be removed in Plone 5.1
```

Note: you need plone.app.z3cform >= 3.0.7 to see that error otherwise you see this
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file widget.py, line 49
```

Can we use RichText from plone.app.textfield.widget instead? Or is it more complicated than that? (I imagine backwards compatibility might be an issue)

**Comment by djowett** [comment]
Ah - sorry this seems to be fixed in 85f24c3 (pending release)
